config/routes.rb
Csc517Program1::Application.routes.draw do
  get "static_pages/search"

  resources :dummy_users

  resources :dummy_posts

  get "users/new"
  root :to => 'static_pages#home'
  match '/signup', to: 'users#new'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/search', to: 'static_pages#search'
  match '/dummy_posts', to: 'static_pages#dummy_posts'
  resources :posts

  resources :users

end

app/models/dummy_user.rb
class DummyUser < ActiveRecord::Base
  attr_accessible :email, :name
end

app/controllers/dummy_users_controller.rb
class DummyUsersController < ApplicationController
  # GET /dummy_users
  # GET /dummy_users.json
  def index
    @dummy_users = DummyUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dummy_users }
    end
  end

  # GET /dummy_users/1
  # GET /dummy_users/1.json
  def show
    @dummy_user = DummyUser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dummy_user }
    end
  end

  # GET /dummy_users/new
  # GET /dummy_users/new.json
  def new
    @dummy_user = DummyUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dummy_user }
    end
  end

  # GET /dummy_users/1/edit
  def edit
    @dummy_user = DummyUser.find(params[:id])
  end

  # POST /dummy_users
  # POST /dummy_users.json
  def create
    @dummy_user = DummyUser.new(params[:dummy_user])

    respond_to do |format|
      if @dummy_user.save
        format.html { redirect_to @dummy_user, notice: 'Dummy user was successfully created.' }
        format.json { render json: @dummy_user, status: :created, location: @dummy_user }
      else
        format.html { render action: "new" }
        format.json { render json: @dummy_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dummy_users/1
  # PUT /dummy_users/1.json
  def update
    @dummy_user = DummyUser.find(params[:id])

    respond_to do |format|
      if @dummy_user.update_attributes(params[:dummy_user])
        format.html { redirect_to @dummy_user, notice: 'Dummy user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dummy_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dummy_users/1
  # DELETE /dummy_users/1.json
  def destroy
    @dummy_user = DummyUser.find(params[:id])
    @dummy_user.destroy

    respond_to do |format|
      format.html { redirect_to dummy_users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dummy_users_helper.rb
module DummyUsersHelper
end

app/views/dummy_users/_form.html.erb
<%= form_for(@dummy_user) do |f| %>
  <% if @dummy_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dummy_user.errors.count, "error") %> prohibited this dummy_user from being saved:</h2>

      <ul>
      <% @dummy_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dummy_users/edit.html.erb
<h1>Editing dummy_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @dummy_user %> |
<%= link_to 'Back', dummy_users_path %>

app/views/dummy_users/index.html.erb
<h1>Listing dummy_users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dummy_users.each do |dummy_user| %>
  <tr>
    <td><%= dummy_user.name %></td>
    <td><%= dummy_user.email %></td>
    <td><%= link_to 'Show', dummy_user %></td>
    <td><%= link_to 'Edit', edit_dummy_user_path(dummy_user) %></td>
    <td><%= link_to 'Destroy', dummy_user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dummy user', new_dummy_user_path %>

app/views/dummy_users/new.html.erb
<h1>New dummy_user</h1>

<%= render 'form' %>

<%= link_to 'Back', dummy_users_path %>

app/views/dummy_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dummy_user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @dummy_user.email %>
</p>


<%= link_to 'Edit', edit_dummy_user_path(@dummy_user) %> |
<%= link_to 'Back', dummy_users_path %>