config/routes.rb
Csc517Program1::Application.routes.draw do
  get "static_pages/search"

  resources :dummy_users

  resources :dummy_posts

  get "users/new"
  root :to => 'static_pages#home'
  match '/signup', to: 'users#new'
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/search', to: 'static_pages#search'
  match '/dummy_posts', to: 'static_pages#dummy_posts'
  resources :posts

  resources :users

end

app/models/dummy_post.rb
class DummyPost < ActiveRecord::Base
  attr_accessible :content, :post, :user_id

  def self.search(search)
    if search
      find(:all, :conditions => ['content LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/dummy_posts_controller.rb
class DummyPostsController < ApplicationController
  # GET /dummy_posts
  # GET /dummy_posts.json
  def index
    #@dummy_posts = DummyPost.all
    @dummy_posts = DummyPost.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dummy_posts }
    end
  end

  # GET /dummy_posts/1
  # GET /dummy_posts/1.json
  def show
    @dummy_post = DummyPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dummy_post }
    end
  end

  # GET /dummy_posts/new
  # GET /dummy_posts/new.json
  def new
    @dummy_post = DummyPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dummy_post }
    end
  end

  # GET /dummy_posts/1/edit
  def edit
    @dummy_post = DummyPost.find(params[:id])
  end

  # POST /dummy_posts
  # POST /dummy_posts.json
  def create
    @dummy_post = DummyPost.new(params[:dummy_post])

    respond_to do |format|
      if @dummy_post.save
        format.html { redirect_to @dummy_post, notice: 'Dummy post was successfully created.' }
        format.json { render json: @dummy_post, status: :created, location: @dummy_post }
      else
        format.html { render action: "new" }
        format.json { render json: @dummy_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dummy_posts/1
  # PUT /dummy_posts/1.json
  def update
    @dummy_post = DummyPost.find(params[:id])

    respond_to do |format|
      if @dummy_post.update_attributes(params[:dummy_post])
        format.html { redirect_to @dummy_post, notice: 'Dummy post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dummy_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dummy_posts/1
  # DELETE /dummy_posts/1.json
  def destroy
    @dummy_post = DummyPost.find(params[:id])
    @dummy_post.destroy

    respond_to do |format|
      format.html { redirect_to dummy_posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dummy_posts_helper.rb
module DummyPostsHelper
end

app/views/dummy_posts/_form.html.erb
<%= form_for(@dummy_post) do |f| %>
  <% if @dummy_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dummy_post.errors.count, "error") %> prohibited this dummy_post from being saved:</h2>

      <ul>
      <% @dummy_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_field :post %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dummy_posts/edit.html.erb
<h1>Editing dummy_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @dummy_post %> |
<%= link_to 'Back', dummy_posts_path %>

app/views/dummy_posts/index.html.erb
<h1>Listing dummy_posts</h1>

<table>
  <tr>
    <th>Post</th>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dummy_posts.each do |dummy_post| %>
  <tr>
    <td><%= dummy_post.post %></td>
    <td><%= dummy_post.content %></td>
    <td><%= dummy_post.user_id %></td>
    <td><%= link_to 'Show', dummy_post %></td>
    <td><%= link_to 'Edit', edit_dummy_post_path(dummy_post) %></td>
    <td><%= link_to 'Destroy', dummy_post, confirm: 'Are you sure?', method: :delete %></td>

  </tr>

<% end %>


  <tr>
    <td>
      <%= form_tag dummy_posts_path, :method => 'get' do %>
          <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag "Search", :name => nil %>
          </p>
      <% end %>
    </td>
  </tr>
</table>

<br />

<%= link_to 'New Dummy post', new_dummy_post_path %>

app/views/dummy_posts/new.html.erb
<h1>New dummy_post</h1>

<%= render 'form' %>

<%= link_to 'Back', dummy_posts_path %>

app/views/dummy_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Post:</b>
  <%= @dummy_post.post %>
</p>

<p>
  <b>Content:</b>
  <%= @dummy_post.content %>
</p>

<p>
  <b>User:</b>
  <%= @dummy_post.user_id %>
</p>


<%= link_to 'Edit', edit_dummy_post_path(@dummy_post) %> |
<%= link_to 'Back', dummy_posts_path %>